In [2]:
import numpy as np

In [3]:
A = np.arange(100)

In [4]:
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [5]:
A[3] = -1200

In [6]:
A

array([    0,     1,     2, -1200,     4,     5,     6,     7,     8,
           9,    10,    11,    12,    13,    14,    15,    16,    17,
          18,    19,    20,    21,    22,    23,    24,    25,    26,
          27,    28,    29,    30,    31,    32,    33,    34,    35,
          36,    37,    38,    39,    40,    41,    42,    43,    44,
          45,    46,    47,    48,    49,    50,    51,    52,    53,
          54,    55,    56,    57,    58,    59,    60,    61,    62,
          63,    64,    65,    66,    67,    68,    69,    70,    71,
          72,    73,    74,    75,    76,    77,    78,    79,    80,
          81,    82,    83,    84,    85,    86,    87,    88,    89,
          90,    91,    92,    93,    94,    95,    96,    97,    98,
          99])

In [9]:
idx = np.argwhere(A==-1200)[0][0]

In [10]:
idx

3

In [11]:
A[idx] = 3

In [12]:
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [15]:
A = np.round(10*np.random.rand(5, 4))

In [16]:
A

array([[ 5.,  1.,  0.,  1.],
       [ 2., 10., 10.,  2.],
       [ 5.,  5., 10.,  8.],
       [ 9.,  2.,  4.,  4.],
       [ 3.,  4.,  6.,  7.]])

In [17]:
A[1][2]

10.0

In [18]:
A[1,:]

array([ 2., 10., 10.,  2.])

In [19]:
A[:, 1]

array([ 1., 10.,  5.,  2.,  4.])

In [21]:
A[1:3, 2:4]

array([[10.,  2.],
       [10.,  8.]])

In [22]:
A

array([[ 5.,  1.,  0.,  1.],
       [ 2., 10., 10.,  2.],
       [ 5.,  5., 10.,  8.],
       [ 9.,  2.,  4.,  4.],
       [ 3.,  4.,  6.,  7.]])

In [23]:
A.T

array([[ 5.,  2.,  5.,  9.,  3.],
       [ 1., 10.,  5.,  2.,  4.],
       [ 0., 10., 10.,  4.,  6.],
       [ 1.,  2.,  8.,  4.,  7.]])

In [24]:
import numpy.linalg as la

In [26]:
B = np.random.rand(3,3)

In [28]:
la.inv(B)

array([[ -2.66029061,  20.09436716,  -4.85551924],
       [-23.91381847,  42.19311862,   1.57073362],
       [ 17.51430322, -40.87241811,   3.39316062]])

In [29]:
B

array([[0.43752528, 0.27486393, 0.49884888],
       [0.22924859, 0.1603825 , 0.25380547],
       [0.50306893, 0.5131412 , 0.77704919]])

In [31]:
A

array([[ 5.,  1.,  0.,  1.],
       [ 2., 10., 10.,  2.],
       [ 5.,  5., 10.,  8.],
       [ 9.,  2.,  4.,  4.],
       [ 3.,  4.,  6.,  7.]])

In [32]:
A.sort(axis=0) # sort columns

In [33]:
A

array([[ 2.,  1.,  0.,  1.],
       [ 3.,  2.,  4.,  2.],
       [ 5.,  4.,  6.,  4.],
       [ 5.,  5., 10.,  7.],
       [ 9., 10., 10.,  8.]])

In [34]:
A.sort(axis=1) # sort rows

In [35]:
A

array([[ 0.,  1.,  1.,  2.],
       [ 2.,  2.,  3.,  4.],
       [ 4.,  4.,  5.,  6.],
       [ 5.,  5.,  7., 10.],
       [ 8.,  9., 10., 10.]])

In [46]:
A = np.arange(100)

In [47]:
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [48]:
B = A[[3, 5, 6]]

In [49]:
B

array([3, 5, 6])

In [50]:
B[0] = -4

In [51]:
B

array([-4,  5,  6])

In [52]:
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [53]:
B = A[A < 40]

In [54]:
B

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [55]:
B = A[(A<40) & (A>30)]

In [56]:
B

array([31, 32, 33, 34, 35, 36, 37, 38, 39])

In [57]:
# ''&' for arrays, 'and' for a single object
# |, or
# ~, not

In [61]:
A = np.arange(4).reshape(2, 2)

In [62]:
A

array([[0, 1],
       [2, 3]])

In [63]:
A = A + 5

In [64]:
A

array([[5, 6],
       [7, 8]])

In [72]:
A = np.arange(4).reshape(2, 2)

In [73]:
A

array([[0, 1],
       [2, 3]])

In [74]:
B = np.arange(1,3)

In [75]:
B

array([1, 2])

In [76]:
A + B

array([[1, 3],
       [3, 5]])

In [77]:
A = np.arange(4).reshape(2,2)

In [81]:
A

array([[0, 1],
       [2, 3]])

In [82]:
C = np.array([[1],[2]])

In [83]:
C

array([[1],
       [2]])

In [84]:
A + C

array([[1, 2],
       [4, 5]])

In [85]:
A = np.round(10*np.random.rand(2, 3))

In [86]:
A

array([[ 3., 10.,  7.],
       [ 9.,  3.,  3.]])

In [87]:
A + 3

array([[ 6., 13., 10.],
       [12.,  6.,  6.]])

In [89]:
A + (np.arange(2).reshape(2, 1))

array([[ 3., 10.,  7.],
       [10.,  4.,  4.]])

In [90]:
B = np.round(10 * np.random.rand(2, 3))

In [91]:
A

array([[ 3., 10.,  7.],
       [ 9.,  3.,  3.]])

In [92]:
B

array([[ 2.,  8., 10.],
       [ 1.,  3.,  6.]])

In [93]:
C = np.hstack((A, B))

In [94]:
C

array([[ 3., 10.,  7.,  2.,  8., 10.],
       [ 9.,  3.,  3.,  1.,  3.,  6.]])

In [97]:
A = np.random.permutation(np.arange(10))

In [98]:
A

array([4, 1, 7, 6, 0, 8, 3, 5, 2, 9])

In [99]:
np.sort(A)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [100]:
A

array([4, 1, 7, 6, 0, 8, 3, 5, 2, 9])

In [101]:
A.sort()

In [102]:
A = A[::-1]

In [103]:
A

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [104]:
A = np.array(["abc", "how are you", "u765", "13er"])

In [105]:
A

array(['abc', 'how are you', 'u765', '13er'], dtype='<U11')

In [106]:
A.sort()

In [107]:
A

array(['13er', 'abc', 'how are you', 'u765'], dtype='<U11')

In [108]:
A = np.round(10*np.random.rand(2, 3))

In [109]:
A

array([[10.,  7.,  0.],
       [ 4.,  6.,  4.]])

In [110]:
B = np.round(10*np.random.rand(2, 3))

In [111]:
B

array([[8., 2., 5.],
       [6., 5., 0.]])

In [112]:
C = np.vstack((A, B))

In [113]:
C

array([[10.,  7.,  0.],
       [ 4.,  6.,  4.],
       [ 8.,  2.,  5.],
       [ 6.,  5.,  0.]])

In [114]:
D = np.round(10*np.random.rand(1, 3))

In [115]:
D

array([[1., 1., 7.]])

In [116]:
E = np.vstack((C, D))

In [118]:
E

array([[10.,  7.,  0.],
       [ 4.,  6.,  4.],
       [ 8.,  2.,  5.],
       [ 6.,  5.,  0.],
       [ 1.,  1.,  7.]])